logging:
  level:
    org.springframework.security: INFO
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://localhost:8082
    es:
      url: http://localhost:8083
    admin:
      url: http://localhost:8084
    resource:
      url: http://localhost:9000
    example:
      url: http://localhost:8443
    security:
      url: http://localhost:9999
