version: '2'
services:
    active_bean_fitness-mongodb:
        container_name: active_bean_fitness-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/active_bean_fitness/mongodb/:/data/db/
